# ??????
spring:
  application:
    name: question-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    store-type: redis
    # 30 ???
  #    timeout: 2592000
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: zwm020610
  # Redis ??
  # todo ????????????
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch ??
  # todo ????????????
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # ????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 9001
  servlet:
    context-path: /api/question
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ????
wx:
  # ??????
  # todo ?????
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # ??????
  # todo ?????
  open:
    appId: xxx
    appSecret: xxx
#miniIo
minio:
  accessKey: miniouser
  secretKey: miniouser
  bucket: oj-system
  endpoint: http://192.168.197.131:19000
  readPath: http://192.168.197.131:19000
#??????
codesandbox:
  type: remote